on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: lablox/lablox.github.io@v1.0.0
        name: build
        
      - name: commit
        run: |
          git config --global user.name Mehran-Baghi
          git config --global user.email ${{ secrets.MHRN_EML }}
          git add -A
          git commit -m "Update imorty.com"
          git push
          git push origin HEAD:main
