on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: pwd && ls -lrtha
        
      - uses: lablox/lablox.github.io@v1.0.7
        name: build
        
      - name: commit
        run: |
          git config --global user.name Mehran-Baghi
          git config --global user.email ${{ secrets.MHRN_EML }}
          git add -A
          git commit -m "Update imorty.com"
          git push origin HEAD:main
